#!/bin/bash

source ~/dotfiles/theme.sh

HYPR_CONF="$HOME/dotfiles/hypr/colors.conf"
ROFI_CONF="$HOME/dotfiles/rofi/colors.rasi"
WAYBAR_CONF="$HOME/dotfiles/waybar/colors.css"
SWAYNC_CONF="$HOME/dotfiles/swaync/colors.css"
GHOSTTY_CONF="$HOME/dotfiles/ghostty/colors"
KITTY_CONF="$HOME/dotfiles/kitty/theme.conf"

ALPHA_DEC=$(printf "%d" "0x${OPACITY}")
ALPHA_FLOAT=$(LC_NUMERIC=C awk "BEGIN {printf \"%.2f\", ${ALPHA_DEC}/255}")

# ---------------------------------------------------------
# HYPRLAND
# ---------------------------------------------------------
if [ "$BLUR_ENABLED" = "true" ]; then BLUR_STATE="yes"; else BLUR_STATE="no"; fi

cat > "$HYPR_CONF" <<EOF
# Generated by update-colors.sh
\$base = 0x${OPACITY}${COLOR_BG}
\$base_solid = 0xff${COLOR_BG}
\$surface = 0x${OPACITY}${COLOR_ALT}
\$surface_solid = 0xff${COLOR_ALT}
\$text = 0xff${COLOR_FG}
\$accent = 0xff${COLOR_ACCENT}
\$urgent = 0xff${COLOR_URGENT}

\$radius_inner = ${RADIUS_INNER}
\$radius_outer = ${RADIUS_OUTER}
\$font = ${FONT_NAME}
\$font_size = ${FONT_SIZE}
\$gaps_in = ${GAPS_IN}
\$gaps_out = ${GAPS_OUT}

\$blur_enabled = ${BLUR_STATE}
EOF
echo "Updated Hyprland"

# ---------------------------------------------------------
# WALLPAPER
# ---------------------------------------------------------
hyprctl hyprpaper preload $WALLPAPER
hyprctl hyprpaper wallpaper ",$WALLPAPER"
hyprctl hyprpaper unload all
echo "Updated wallpaper"

# ---------------------------------------------------------
# GTK
# ---------------------------------------------------------
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
gsettings set org.gnome.desktop.interface icon-theme "$ICON_THEME"
#gsettings set org.gnome.desktop.interface font-name "$FONT_NAME $FONT_SIZE_SMALL"
echo "Updated GTK"

# ---------------------------------------------------------
# ROFI
# ---------------------------------------------------------
cat > "$ROFI_CONF" <<EOF
/* Generated by update-colors.sh */
* {
    base: #${COLOR_BG}${OPACITY};
    base-solid: #${COLOR_BG};
    surface: #${COLOR_ALT}${OPACITY};
    surface-solid: #${COLOR_ALT};
    text: #${COLOR_FG};
    accent: #${COLOR_ACCENT};
    urgent: #${COLOR_URGENT};
    result-color: #${COLOR_SUCCESS};

    font: "${FONT_NAME} ${FONT_SIZE}";
    radius-inner: ${RADIUS_INNER}px;
    radius-outer: ${RADIUS_OUTER}px;
    padding-0: ${PADDING_0}px;
    padding-1: ${PADDING_1}px;
    padding-2: ${PADDING_2}px;
    padding-3: ${PADDING_3}px;
    border-size: ${BORDER}px;

    background-color: @base;
    text-color: @text;
}
EOF
echo "Updated rofi"

# ---------------------------------------------------------
# WAYBAR & SWAYNC
# ---------------------------------------------------------
CSS_CONTENT=$(cat <<EOF
/* Generated by update-colors.sh */
@define-color base-solid #${COLOR_BG};
@define-color base alpha(@base-solid, ${ALPHA_FLOAT});
@define-color surface-solid #${COLOR_ALT};
@define-color surface alpha(@surface-solid, ${ALPHA_FLOAT});
@define-color text #${COLOR_FG};
@define-color accent #${COLOR_ACCENT};
@define-color urgent #${COLOR_URGENT};
@define-color good #${COLOR_SUCCESS};

* {
    font-family: "${FONT_NAME}";
    font-size: ${FONT_SIZE}px;
}
EOF
)

echo "$CSS_CONTENT" > "$WAYBAR_CONF"
echo "$CSS_CONTENT" > "$SWAYNC_CONF"

TEMPLATE="$HOME/dotfiles/waybar/style.template.css"
TARGET="$HOME/dotfiles/waybar/style.css"

if [ -f "$TEMPLATE" ]; then
    sed -e "s/@radius-outer/${RADIUS_OUTER}px/g" \
        -e "s/@radius-inner/${RADIUS_INNER}px/g" \
        -e "s/@padding-0/${PADDING_0}px/g" \
        -e "s/@padding-1/${PADDING_1}px/g" \
        -e "s/@padding-2/${PADDING_2}px/g" \
        -e "s/@padding-3/${PADDING_3}px/g" \
        -e "s/@padding-4/${PADDING_4}px/g" \
        -e "s/@gaps-out/${GAPS_OUT}px/g" \
        -e "s/@gaps-in/${GAPS_IN}px/g" \
        "$TEMPLATE" > "$TARGET"
    echo "Updated waybar"
else
    echo "No waybar style.template.css. Skipping."
fi

TEMPLATE="$HOME/dotfiles/swaync/style.template.css"
TARGET="$HOME/dotfiles/swaync/style.css"

if [ -f "$TEMPLATE" ]; then
    sed -e "s/@radius-outer/${RADIUS_OUTER}px/g" \
        -e "s/@radius-inner/${RADIUS_INNER}px/g" \
        -e "s/@padding-0/${PADDING_0}px/g" \
        -e "s/@padding-1/${PADDING_1}px/g" \
        -e "s/@padding-2/${PADDING_2}px/g" \
        -e "s/@padding-3/${PADDING_3}px/g" \
        -e "s/@padding-4/${PADDING_4}px/g" \
        -e "s/@gaps-out/${GAPS_OUT}px/g" \
        -e "s/@gaps-in/${GAPS_IN}px/g" \
        "$TEMPLATE" > "$TARGET"
    echo "Updated swaync"
else
    echo "No swaync style.template.css. Skipping."
fi


# ---------------------------------------------------------
# GHOSTTY
# ---------------------------------------------------------
cat > "$GHOSTTY_CONF" <<EOF
# Generated by update-colors.sh

background = #$COLOR_BG
foreground = #$COLOR_FG

cursor-color = #$COLOR_FG
selection-background = #$COLOR_ACCENT
selection-foreground = #$COLOR_BG

background-opacity = $ALPHA_FLOAT

# Black (Mantle / Alt)
palette = 0=#$COLOR_ALT
palette = 8=#$COLOR_ALT

# Red (Urgent / Error)
palette = 1=#$COLOR_URGENT
palette = 9=#$COLOR_URGENT

# Green (Success)
palette = 2=#$COLOR_SUCCESS
palette = 10=#$COLOR_SUCCESS

# Blue (Accent)
palette = 4=#$COLOR_ACCENT
palette = 12=#$COLOR_ACCENT

macos-titlebar-style = hidden
gtk-titlebar = false
EOF
echo "Updated ghostty"

# ---------------------------------------------------------
# KITTY
# ---------------------------------------------------------
cat > "$KITTY_CONF" <<EOF
# Generated by update-colors.sh

background_opacity $ALPHA_FLOAT
window_padding_width 10
hide_window_decorations yes

font_family      $FONT_NAME
font_size        $FONT_SIZE

background #$COLOR_BG
foreground #$COLOR_FG

selection_background #$COLOR_ACCENT
selection_foreground #$COLOR_BG

url_color #$COLOR_ACCENT
cursor    #$COLOR_ACCENT
cursor_text_color #$COLOR_BG

color0 #$COLOR_ALT
color8 #$COLOR_ALT

color1 #$COLOR_URGENT
color9 #$COLOR_URGENT

color2 #$COLOR_SUCCESS
color10 #$COLOR_SUCCESS

color3 #$COLOR_ACCENT
color11 #$COLOR_ACCENT

color4 #$COLOR_ACCENT
color12 #$COLOR_ACCENT

color5 #$COLOR_URGENT
color13 #$COLOR_URGENT

color6 #$COLOR_ACCENT
color14 #$COLOR_ACCENT

color7 #$COLOR_FG
color15 #$COLOR_FG
EOF

echo "Updated kitty"

hyprctl reload
pkill waybar && waybar & disown > /dev/null
swaync-client -rs
killall -SIGUSR1 kitty 2>/dev/null

echo "Theme updated!"
