music_directory "~/music"
db_file "~/.mpd/database"
log_file "~/.mpd/log"
pid_file "~/.mpd/pid"
state_file "~/.mpd/state"

bind_to_address "~/.mpd/socket"
bind_to_address "127.0.0.1"

auto_update	"yes"
auto_update_depth "3"

input {
  plugin "curl"
}

audio_output {
  type "pipewire"
  name "PipeWire Sound Server"
}

audio_output {
  type "fifo"
  name "my_fifo"
  path "/tmp/mpd.fifo"
  format "44100:16:2"
}
