require("plugins-setup")
require("config").setup()

require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.lspzero")
require("plugins.autopairs")
require("plugins.treesitter" )
