$mainMod = SUPER
$secondaryMod = ALT

bind = $mainMod, Return, exec, uwsm app -- kitty
bind = $mainMod, Q, killactive
bind = $mainMod, B, togglefloating,
bind = $mainMod, SPACE, exec, nc -U /run/user/1000/walker/walker.sock
bind = $mainMod SHIFT, E, exec, uwsm app -- hyprshot -m region --clipboard-only

bind = $mainMod, grave, cyclenext
bind = $mainMod, grave, bringactivetotop

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod SHIFT, Return, exec, kitten quick-access-terminal

bind = SUPER, C, sendshortcut, CTRL, Insert, activewindow
bind = SUPER, V, sendshortcut, SHIFT, Insert, activewindow
bind = SUPER, X, sendshortcut, CTRL, X, activewindow
bind = SUPER, S, sendshortcut, CTRL, S, activewindow
bind = SUPER, A, sendshortcut, CTRL, A, activewindow
bind = SUPER, F, sendshortcut, CTRL, F, activewindow
bind = SUPER, Z, sendshortcut, CTRL, Z, activewindow
bind = SUPER SHIFT, Z, sendshortcut, CTRL SHIFT, Z, activewindow
bind = SUPER, T, sendshortcut, CTRL, T, activewindow
bind = SUPER, W, sendshortcut, CTRL, W, activewindow
bind = SUPER, N, sendshortcut, CTRL, N, activewindow
bind = SUPER, R, sendshortcut, CTRL, R, activewindow
