source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/window_rules.conf

monitor=desc: GIGA-BYTE TECHNOLOGY CO. LTD. M27UP 0x01010101,3840x2160@144,0x0,1.5
monitor=desc: AOC 24G2W1G4 ATNM91A034385,1920x1080@144,2560x0,1

xwayland {
  force_zero_scaling = true
  enabled = false
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

input {
    kb_layout = pl

    follow_mouse = 1
    accel_profile = flat
    force_no_accel = 0
    sensitivity = -0.8
}
