# system
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = float,class:^RAIL,xwayland:1
windowrule = opacity 0.97 0.9, class:.*
windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 875 600, tag:floating-window

windowrule = opacity 1 1, class:^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$

# workspaces
windowrulev2 = workspace 1, class:^(zen.*)$
windowrulev2 = workspace 2, class:^(jetbrains-idea.*)$
windowrulev2 = workspace 2, class:^(Cursor)$
windowrulev2 = workspace 3, class:^(vesktop)$
windowrulev2 = workspace 3, class:^(cider)$

workspace = 1, monitor:desc:GIGA-BYTE TECHNOLOGY CO. LTD. M27UP 0x01010101
workspace = 2, monitor:desc:GIGA-BYTE TECHNOLOGY CO. LTD. M27UP 0x01010101
workspace = 3, monitor:desc:AOC 24G2W1G4 ATNM91A034385

# 1password
windowrule = noscreenshare, class:^(1[p|P]assword)$
windowrule = tag +floating-window, class:^(1[p|P]assword)$

# walker
layerrule = noanim, walker

# misc
windowrule = float,title:.*Minecraft.*
