--enable-features=WaylandWindowDecorations,AllowQt,UseOzonePlatform,VaapiVideoDecoder,VaapiVideoEncoder,CanvasOopRasterization
--enable-wayland-ime
--ozone-platform=wayland
--ozone-platform-hint=auto
--enable-gpu-rasterization
--enable-zero-copy
--disable-gpu-driver-bug-workarounds
