bold_font auto
italic_font auto
bold_italic_font auto
enable_audio_bell no

tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

hide_window_decorations yes
notify_on_cmd_finish invisible 20

shell /bin/nu

allow_remote_control socket-only
listen_on unix:@kitty

cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

map super+c copy_to_clipboard
map super+v paste_from_clipboard

include ./theme.conf
