monitor.alsa.rules = [
  {
    matches = [
      {
        "device.name" = "alsa_card.usb-SteelSeries_Arctis_Nova_7-00"
      }
    ]
    actions = {
      update-props = {
        "device.profile" = "output:analog-stereo"
      }
    }
  }
]
